/**
 * Rosatom REST Api
 * Апи
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.gitpub.rosatom.models

import com.google.gson.annotations.SerializedName

/**
 * Приложение
 * @param author
 * @param id Ид
 * @param name Название
 */

data class AttachmentModel(
    @SerializedName("author")
    val author: UserModel? = null,
    /* Ид */
    @SerializedName("id")
    val id: Long? = null,
    /* Название */
    @SerializedName("name")
    val name: String? = null,
    /* Ссылка на изображение */
    @SerializedName("url")
    val url: String? = null
)

