/**
 * Rosatom REST Api
 * Апи
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.gitpub.rosatom.models


import com.google.gson.annotations.SerializedName

/**
 *
 * @param authorId Ид автора комментария
 * @param content Сам коммент
 */

data class CommentResource(
    /* Ид автора комментария */
    @SerializedName("authorId")
    val authorId: Long,
    /* Сам коммент */
    @SerializedName("content")
    val content: String,
    @SerializedName("closing")
    val closing: Boolean = false
)

