/**
 * Rosatom REST Api
 * Апи
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.gitpub.rosatom.models


import com.google.gson.annotations.SerializedName

/**
 *
 * @param page
 * @param size
 * @param sort
 */

data class Pageable(
    @SerializedName("page")
    val page: Int? = null,
    @SerializedName("size")
    val size: Int? = null,
    @SerializedName("sort")
    val sort: Sort? = null
)

