/**
 * Rosatom REST Api
 * Апи
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.gitpub.rosatom.models

import com.google.gson.annotations.SerializedName

/**
 *
 * @param content
 * @param empty
 * @param first
 * @param last
 * @param number
 * @param numberOfElements
 * @param pageable
 * @param size
 * @param sort
 * @param totalElements
 * @param totalPages
 */

data class PageTaskModel(
    @SerializedName("content")
    val content: List<TaskModel>? = null,
    @SerializedName("empty")
    val empty: Boolean? = null,
    @SerializedName("first")
    val first: Boolean? = null,
    @SerializedName("last")
    val last: Boolean? = null,
    @SerializedName("number")
    val number: Int? = null,
    @SerializedName("numberOfElements")
    val numberOfElements: Int? = null,
    @SerializedName("pageable")
    val pageable: Pageable? = null,
    @SerializedName("size")
    val size: Int? = null,
    @SerializedName("sort")
    val sort: Sort? = null,
    @SerializedName("totalElements")
    val totalElements: Long? = null,
    @SerializedName("totalPages")
    val totalPages: Int? = null
)

