/**
 * Rosatom REST Api
 * Апи
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.gitpub.rosatom.models

import com.google.gson.annotations.SerializedName
import org.joda.time.DateTime

/**
 * Задача
 * @param assignee
 * @param attachments Приложенные файлы
 * @param author
 * @param comments Комментарии
 * @param dateFact Фактическая дата\\время выполнения
 * @param dateTo Необходимая дата\\время выполнения
 * @param header Заголовок
 * @param id Ид
 * @param info Содержание задачи
 * @param priority
 * @param status
 * @param subTaskList Подзадачи
 * @param tstmpCreate Время создания задачи
 * @param type
 */

data class TaskModel(
    @SerializedName("assignee")
    val assignee: UserModel? = null,
    /* Приложенные файлы */
    @SerializedName("attachments")
    val attachments: List<AttachmentModel>? = null,
    @SerializedName("author")
    val author: UserModel? = null,
    /* Комментарии */
    @SerializedName("comments")
    val comments: List<CommentModel>? = null,
    /* Фактическая дата\\время выполнения */
    @SerializedName("dateFact")
    val dateFact: DateTime? = null,
    /* Необходимая дата\\время выполнения */
    @SerializedName("dateTo")
    val dateTo: DateTime? = null,
    /* Заголовок */
    @SerializedName("header")
    val header: String? = null,
    /* Ид */
    @SerializedName("id")
    val id: Long? = null,
    /* Содержание задачи */
    @SerializedName("info")
    val info: String? = null,
    @SerializedName("priority")
    val priority: PriorityModel? = null,
    @SerializedName("status")
    val status: StatusTypeModel? = null,
    /* Подзадачи */
    @SerializedName("subTaskList")
    val subTaskList: List<TaskModel>? = null,
    /* Время создания задачи */
    @SerializedName("tstmpCreate")
    val tstmpCreate: DateTime? = null,
    @SerializedName("type")
    val type: TaskTypeModel? = null,
    @SerializedName("group")
    val group: GroupModel? = null
)
