/**
 * Rosatom REST Api
 * Апи
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.gitpub.rosatom.models


import com.google.gson.annotations.SerializedName
import org.joda.time.DateTime

/**
 *
 * @param assignee Ид исполнителя
 * @param dateFact Фактическая дата\\время выполнения
 * @param dateTo Необходимая дата\\время выполнения
 * @param header Заголовок
 * @param priority Ид приоритета
 * @param type Ид типа задачи
 * @param author Ид автора задачи
 * @param info Содержание задачи
 * @param parent Ид родительской задачи
 */

data class TaskResource(
    /* Ид исполнителя */
    @SerializedName("assignee")
    val assignee: Long,
    /* Фактическая дата\\время выполнения */
    @SerializedName("dateFact")
    val dateFact: DateTime,
    /* Необходимая дата\\время выполнения */
    @SerializedName("dateTo")
    val dateTo: DateTime,
    /* Заголовок */
    @SerializedName("header")
    val header: String,
    /* Ид приоритета */
    @SerializedName("priority")
    val priority: Long,
    /* Ид типа задачи */
    @SerializedName("type")
    val type: Long,
    /* Ид автора задачи */
    @SerializedName("author")
    val author: Long? = null,
    /* Содержание задачи */
    @SerializedName("info")
    val info: String? = null,
    /* Ид родительской задачи */
    @SerializedName("parent")
    val parent: Long? = null
)

