/**
 * Rosatom REST Api
 * Апи
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.gitpub.rosatom.models

import com.google.gson.annotations.SerializedName

/**
 * Пользователь
 * @param id Ид
 * @param name ФИО
 * @param position
 * @param type Группа пользователей\\конкретный пользователь
 */

data class UserModel(
    /* Ид */
    @SerializedName("id")
    val id: Long? = null,
    /* ФИО */
    @SerializedName("name")
    val name: String? = null,
    @SerializedName("position")
    val position: PositionModel? = null,
    /* Группа пользователей\\конкретный пользователь */
    @SerializedName("type")
    val type: Long? = null
)

